
# Create wordclouds

mkdir output/simulation/Distal_radius_fractures_approach_expert_inclusion/
mkdir output/simulation/Distal_radius_fractures_approach_expert_inclusion/descriptives
asreview wordcloud data/Distal_radius_fractures_approach_expert_inclusion.csv -o output/simulation/Distal_radius_fractures_approach_expert_inclusion/descriptives/wordcloud_Distal_radius_fractures_approach_expert_inclusion.png --width 800 --height 500
asreview wordcloud data/Distal_radius_fractures_approach_expert_inclusion.csv -o output/simulation/Distal_radius_fractures_approach_expert_inclusion/descriptives/wordcloud_Distal_radius_fractures_approach_expert_inclusion_relevant.png --width 800 --height 500 --relevant
asreview wordcloud data/Distal_radius_fractures_approach_expert_inclusion.csv -o output/simulation/Distal_radius_fractures_approach_expert_inclusion/descriptives/wordcloud_Distal_radius_fractures_approach_expert_inclusion_irrelevant.png --width 800 --height 500 --irrelevant

mkdir output/simulation/Distal_radius_fractures_approach_fulltext_inclusion/
mkdir output/simulation/Distal_radius_fractures_approach_fulltext_inclusion/descriptives
asreview wordcloud data/Distal_radius_fractures_approach_fulltext_inclusion.csv -o output/simulation/Distal_radius_fractures_approach_fulltext_inclusion/descriptives/wordcloud_Distal_radius_fractures_approach_fulltext_inclusion.png --width 800 --height 500
asreview wordcloud data/Distal_radius_fractures_approach_fulltext_inclusion.csv -o output/simulation/Distal_radius_fractures_approach_fulltext_inclusion/descriptives/wordcloud_Distal_radius_fractures_approach_fulltext_inclusion_relevant.png --width 800 --height 500 --relevant
asreview wordcloud data/Distal_radius_fractures_approach_fulltext_inclusion.csv -o output/simulation/Distal_radius_fractures_approach_fulltext_inclusion/descriptives/wordcloud_Distal_radius_fractures_approach_fulltext_inclusion_irrelevant.png --width 800 --height 500 --irrelevant

mkdir output/simulation/Distal_radius_fractures_approach_noisy_inclusion/
mkdir output/simulation/Distal_radius_fractures_approach_noisy_inclusion/descriptives
asreview wordcloud data/Distal_radius_fractures_approach_noisy_inclusion.csv -o output/simulation/Distal_radius_fractures_approach_noisy_inclusion/descriptives/wordcloud_Distal_radius_fractures_approach_noisy_inclusion.png --width 800 --height 500
asreview wordcloud data/Distal_radius_fractures_approach_noisy_inclusion.csv -o output/simulation/Distal_radius_fractures_approach_noisy_inclusion/descriptives/wordcloud_Distal_radius_fractures_approach_noisy_inclusion_relevant.png --width 800 --height 500 --relevant
asreview wordcloud data/Distal_radius_fractures_approach_noisy_inclusion.csv -o output/simulation/Distal_radius_fractures_approach_noisy_inclusion/descriptives/wordcloud_Distal_radius_fractures_approach_noisy_inclusion_irrelevant.png --width 800 --height 500 --irrelevant

mkdir output/simulation/Distal_radius_fractures_closed_reduction_expert_inclusion/
mkdir output/simulation/Distal_radius_fractures_closed_reduction_expert_inclusion/descriptives
asreview wordcloud data/Distal_radius_fractures_closed_reduction_expert_inclusion.csv -o output/simulation/Distal_radius_fractures_closed_reduction_expert_inclusion/descriptives/wordcloud_Distal_radius_fractures_closed_reduction_expert_inclusion.png --width 800 --height 500
asreview wordcloud data/Distal_radius_fractures_closed_reduction_expert_inclusion.csv -o output/simulation/Distal_radius_fractures_closed_reduction_expert_inclusion/descriptives/wordcloud_Distal_radius_fractures_closed_reduction_expert_inclusion_relevant.png --width 800 --height 500 --relevant
asreview wordcloud data/Distal_radius_fractures_closed_reduction_expert_inclusion.csv -o output/simulation/Distal_radius_fractures_closed_reduction_expert_inclusion/descriptives/wordcloud_Distal_radius_fractures_closed_reduction_expert_inclusion_irrelevant.png --width 800 --height 500 --irrelevant

mkdir output/simulation/Distal_radius_fractures_closed_reduction_fulltext_inclusion/
mkdir output/simulation/Distal_radius_fractures_closed_reduction_fulltext_inclusion/descriptives
asreview wordcloud data/Distal_radius_fractures_closed_reduction_fulltext_inclusion.csv -o output/simulation/Distal_radius_fractures_closed_reduction_fulltext_inclusion/descriptives/wordcloud_Distal_radius_fractures_closed_reduction_fulltext_inclusion.png --width 800 --height 500
asreview wordcloud data/Distal_radius_fractures_closed_reduction_fulltext_inclusion.csv -o output/simulation/Distal_radius_fractures_closed_reduction_fulltext_inclusion/descriptives/wordcloud_Distal_radius_fractures_closed_reduction_fulltext_inclusion_relevant.png --width 800 --height 500 --relevant
asreview wordcloud data/Distal_radius_fractures_closed_reduction_fulltext_inclusion.csv -o output/simulation/Distal_radius_fractures_closed_reduction_fulltext_inclusion/descriptives/wordcloud_Distal_radius_fractures_closed_reduction_fulltext_inclusion_irrelevant.png --width 800 --height 500 --irrelevant

mkdir output/simulation/Distal_radius_fractures_closed_reduction_noisy_inclusion/
mkdir output/simulation/Distal_radius_fractures_closed_reduction_noisy_inclusion/descriptives
asreview wordcloud data/Distal_radius_fractures_closed_reduction_noisy_inclusion.csv -o output/simulation/Distal_radius_fractures_closed_reduction_noisy_inclusion/descriptives/wordcloud_Distal_radius_fractures_closed_reduction_noisy_inclusion.png --width 800 --height 500
asreview wordcloud data/Distal_radius_fractures_closed_reduction_noisy_inclusion.csv -o output/simulation/Distal_radius_fractures_closed_reduction_noisy_inclusion/descriptives/wordcloud_Distal_radius_fractures_closed_reduction_noisy_inclusion_relevant.png --width 800 --height 500 --relevant
asreview wordcloud data/Distal_radius_fractures_closed_reduction_noisy_inclusion.csv -o output/simulation/Distal_radius_fractures_closed_reduction_noisy_inclusion/descriptives/wordcloud_Distal_radius_fractures_closed_reduction_noisy_inclusion_irrelevant.png --width 800 --height 500 --irrelevant

mkdir output/simulation/Hallux_valgus_prognostic_expert_inclusion/
mkdir output/simulation/Hallux_valgus_prognostic_expert_inclusion/descriptives
asreview wordcloud data/Hallux_valgus_prognostic_expert_inclusion.csv -o output/simulation/Hallux_valgus_prognostic_expert_inclusion/descriptives/wordcloud_Hallux_valgus_prognostic_expert_inclusion.png --width 800 --height 500
asreview wordcloud data/Hallux_valgus_prognostic_expert_inclusion.csv -o output/simulation/Hallux_valgus_prognostic_expert_inclusion/descriptives/wordcloud_Hallux_valgus_prognostic_expert_inclusion_relevant.png --width 800 --height 500 --relevant
asreview wordcloud data/Hallux_valgus_prognostic_expert_inclusion.csv -o output/simulation/Hallux_valgus_prognostic_expert_inclusion/descriptives/wordcloud_Hallux_valgus_prognostic_expert_inclusion_irrelevant.png --width 800 --height 500 --irrelevant

mkdir output/simulation/Hallux_valgus_prognostic_fulltext_inclusion/
mkdir output/simulation/Hallux_valgus_prognostic_fulltext_inclusion/descriptives
asreview wordcloud data/Hallux_valgus_prognostic_fulltext_inclusion.csv -o output/simulation/Hallux_valgus_prognostic_fulltext_inclusion/descriptives/wordcloud_Hallux_valgus_prognostic_fulltext_inclusion.png --width 800 --height 500
asreview wordcloud data/Hallux_valgus_prognostic_fulltext_inclusion.csv -o output/simulation/Hallux_valgus_prognostic_fulltext_inclusion/descriptives/wordcloud_Hallux_valgus_prognostic_fulltext_inclusion_relevant.png --width 800 --height 500 --relevant
asreview wordcloud data/Hallux_valgus_prognostic_fulltext_inclusion.csv -o output/simulation/Hallux_valgus_prognostic_fulltext_inclusion/descriptives/wordcloud_Hallux_valgus_prognostic_fulltext_inclusion_irrelevant.png --width 800 --height 500 --irrelevant

mkdir output/simulation/Hallux_valgus_prognostic_noisy_inclusion/
mkdir output/simulation/Hallux_valgus_prognostic_noisy_inclusion/descriptives
asreview wordcloud data/Hallux_valgus_prognostic_noisy_inclusion.csv -o output/simulation/Hallux_valgus_prognostic_noisy_inclusion/descriptives/wordcloud_Hallux_valgus_prognostic_noisy_inclusion.png --width 800 --height 500
asreview wordcloud data/Hallux_valgus_prognostic_noisy_inclusion.csv -o output/simulation/Hallux_valgus_prognostic_noisy_inclusion/descriptives/wordcloud_Hallux_valgus_prognostic_noisy_inclusion_relevant.png --width 800 --height 500 --relevant
asreview wordcloud data/Hallux_valgus_prognostic_noisy_inclusion.csv -o output/simulation/Hallux_valgus_prognostic_noisy_inclusion/descriptives/wordcloud_Hallux_valgus_prognostic_noisy_inclusion_irrelevant.png --width 800 --height 500 --irrelevant

mkdir output/simulation/Head_and_neck_cancer_bone_expert_inclusion/
mkdir output/simulation/Head_and_neck_cancer_bone_expert_inclusion/descriptives
asreview wordcloud data/Head_and_neck_cancer_bone_expert_inclusion.csv -o output/simulation/Head_and_neck_cancer_bone_expert_inclusion/descriptives/wordcloud_Head_and_neck_cancer_bone_expert_inclusion.png --width 800 --height 500
asreview wordcloud data/Head_and_neck_cancer_bone_expert_inclusion.csv -o output/simulation/Head_and_neck_cancer_bone_expert_inclusion/descriptives/wordcloud_Head_and_neck_cancer_bone_expert_inclusion_relevant.png --width 800 --height 500 --relevant
asreview wordcloud data/Head_and_neck_cancer_bone_expert_inclusion.csv -o output/simulation/Head_and_neck_cancer_bone_expert_inclusion/descriptives/wordcloud_Head_and_neck_cancer_bone_expert_inclusion_irrelevant.png --width 800 --height 500 --irrelevant

mkdir output/simulation/Head_and_neck_cancer_bone_fulltext_inclusion/
mkdir output/simulation/Head_and_neck_cancer_bone_fulltext_inclusion/descriptives
asreview wordcloud data/Head_and_neck_cancer_bone_fulltext_inclusion.csv -o output/simulation/Head_and_neck_cancer_bone_fulltext_inclusion/descriptives/wordcloud_Head_and_neck_cancer_bone_fulltext_inclusion.png --width 800 --height 500
asreview wordcloud data/Head_and_neck_cancer_bone_fulltext_inclusion.csv -o output/simulation/Head_and_neck_cancer_bone_fulltext_inclusion/descriptives/wordcloud_Head_and_neck_cancer_bone_fulltext_inclusion_relevant.png --width 800 --height 500 --relevant
asreview wordcloud data/Head_and_neck_cancer_bone_fulltext_inclusion.csv -o output/simulation/Head_and_neck_cancer_bone_fulltext_inclusion/descriptives/wordcloud_Head_and_neck_cancer_bone_fulltext_inclusion_irrelevant.png --width 800 --height 500 --irrelevant

mkdir output/simulation/Head_and_neck_cancer_bone_noisy_inclusion/
mkdir output/simulation/Head_and_neck_cancer_bone_noisy_inclusion/descriptives
asreview wordcloud data/Head_and_neck_cancer_bone_noisy_inclusion.csv -o output/simulation/Head_and_neck_cancer_bone_noisy_inclusion/descriptives/wordcloud_Head_and_neck_cancer_bone_noisy_inclusion.png --width 800 --height 500
asreview wordcloud data/Head_and_neck_cancer_bone_noisy_inclusion.csv -o output/simulation/Head_and_neck_cancer_bone_noisy_inclusion/descriptives/wordcloud_Head_and_neck_cancer_bone_noisy_inclusion_relevant.png --width 800 --height 500 --relevant
asreview wordcloud data/Head_and_neck_cancer_bone_noisy_inclusion.csv -o output/simulation/Head_and_neck_cancer_bone_noisy_inclusion/descriptives/wordcloud_Head_and_neck_cancer_bone_noisy_inclusion_irrelevant.png --width 800 --height 500 --irrelevant

mkdir output/simulation/Head_and_neck_cancer_imaging_expert_inclusion/
mkdir output/simulation/Head_and_neck_cancer_imaging_expert_inclusion/descriptives
asreview wordcloud data/Head_and_neck_cancer_imaging_expert_inclusion.csv -o output/simulation/Head_and_neck_cancer_imaging_expert_inclusion/descriptives/wordcloud_Head_and_neck_cancer_imaging_expert_inclusion.png --width 800 --height 500
asreview wordcloud data/Head_and_neck_cancer_imaging_expert_inclusion.csv -o output/simulation/Head_and_neck_cancer_imaging_expert_inclusion/descriptives/wordcloud_Head_and_neck_cancer_imaging_expert_inclusion_relevant.png --width 800 --height 500 --relevant
asreview wordcloud data/Head_and_neck_cancer_imaging_expert_inclusion.csv -o output/simulation/Head_and_neck_cancer_imaging_expert_inclusion/descriptives/wordcloud_Head_and_neck_cancer_imaging_expert_inclusion_irrelevant.png --width 800 --height 500 --irrelevant

mkdir output/simulation/Head_and_neck_cancer_imaging_fulltext_inclusion/
mkdir output/simulation/Head_and_neck_cancer_imaging_fulltext_inclusion/descriptives
asreview wordcloud data/Head_and_neck_cancer_imaging_fulltext_inclusion.csv -o output/simulation/Head_and_neck_cancer_imaging_fulltext_inclusion/descriptives/wordcloud_Head_and_neck_cancer_imaging_fulltext_inclusion.png --width 800 --height 500
asreview wordcloud data/Head_and_neck_cancer_imaging_fulltext_inclusion.csv -o output/simulation/Head_and_neck_cancer_imaging_fulltext_inclusion/descriptives/wordcloud_Head_and_neck_cancer_imaging_fulltext_inclusion_relevant.png --width 800 --height 500 --relevant
asreview wordcloud data/Head_and_neck_cancer_imaging_fulltext_inclusion.csv -o output/simulation/Head_and_neck_cancer_imaging_fulltext_inclusion/descriptives/wordcloud_Head_and_neck_cancer_imaging_fulltext_inclusion_irrelevant.png --width 800 --height 500 --irrelevant

mkdir output/simulation/Head_and_neck_cancer_imaging_noisy_inclusion/
mkdir output/simulation/Head_and_neck_cancer_imaging_noisy_inclusion/descriptives
asreview wordcloud data/Head_and_neck_cancer_imaging_noisy_inclusion.csv -o output/simulation/Head_and_neck_cancer_imaging_noisy_inclusion/descriptives/wordcloud_Head_and_neck_cancer_imaging_noisy_inclusion.png --width 800 --height 500
asreview wordcloud data/Head_and_neck_cancer_imaging_noisy_inclusion.csv -o output/simulation/Head_and_neck_cancer_imaging_noisy_inclusion/descriptives/wordcloud_Head_and_neck_cancer_imaging_noisy_inclusion_relevant.png --width 800 --height 500 --relevant
asreview wordcloud data/Head_and_neck_cancer_imaging_noisy_inclusion.csv -o output/simulation/Head_and_neck_cancer_imaging_noisy_inclusion/descriptives/wordcloud_Head_and_neck_cancer_imaging_noisy_inclusion_irrelevant.png --width 800 --height 500 --irrelevant

mkdir output/simulation/Obstetric_emergency_training_expert_inclusion/
mkdir output/simulation/Obstetric_emergency_training_expert_inclusion/descriptives
asreview wordcloud data/Obstetric_emergency_training_expert_inclusion.csv -o output/simulation/Obstetric_emergency_training_expert_inclusion/descriptives/wordcloud_Obstetric_emergency_training_expert_inclusion.png --width 800 --height 500
asreview wordcloud data/Obstetric_emergency_training_expert_inclusion.csv -o output/simulation/Obstetric_emergency_training_expert_inclusion/descriptives/wordcloud_Obstetric_emergency_training_expert_inclusion_relevant.png --width 800 --height 500 --relevant
asreview wordcloud data/Obstetric_emergency_training_expert_inclusion.csv -o output/simulation/Obstetric_emergency_training_expert_inclusion/descriptives/wordcloud_Obstetric_emergency_training_expert_inclusion_irrelevant.png --width 800 --height 500 --irrelevant

mkdir output/simulation/Obstetric_emergency_training_fulltext_inclusion/
mkdir output/simulation/Obstetric_emergency_training_fulltext_inclusion/descriptives
asreview wordcloud data/Obstetric_emergency_training_fulltext_inclusion.csv -o output/simulation/Obstetric_emergency_training_fulltext_inclusion/descriptives/wordcloud_Obstetric_emergency_training_fulltext_inclusion.png --width 800 --height 500
asreview wordcloud data/Obstetric_emergency_training_fulltext_inclusion.csv -o output/simulation/Obstetric_emergency_training_fulltext_inclusion/descriptives/wordcloud_Obstetric_emergency_training_fulltext_inclusion_relevant.png --width 800 --height 500 --relevant
asreview wordcloud data/Obstetric_emergency_training_fulltext_inclusion.csv -o output/simulation/Obstetric_emergency_training_fulltext_inclusion/descriptives/wordcloud_Obstetric_emergency_training_fulltext_inclusion_irrelevant.png --width 800 --height 500 --irrelevant

mkdir output/simulation/Obstetric_emergency_training_noisy_inclusion/
mkdir output/simulation/Obstetric_emergency_training_noisy_inclusion/descriptives
asreview wordcloud data/Obstetric_emergency_training_noisy_inclusion.csv -o output/simulation/Obstetric_emergency_training_noisy_inclusion/descriptives/wordcloud_Obstetric_emergency_training_noisy_inclusion.png --width 800 --height 500
asreview wordcloud data/Obstetric_emergency_training_noisy_inclusion.csv -o output/simulation/Obstetric_emergency_training_noisy_inclusion/descriptives/wordcloud_Obstetric_emergency_training_noisy_inclusion_relevant.png --width 800 --height 500 --relevant
asreview wordcloud data/Obstetric_emergency_training_noisy_inclusion.csv -o output/simulation/Obstetric_emergency_training_noisy_inclusion/descriptives/wordcloud_Obstetric_emergency_training_noisy_inclusion_irrelevant.png --width 800 --height 500 --irrelevant

mkdir output/simulation/Post_intensive_care_treatment_expert_inclusion/
mkdir output/simulation/Post_intensive_care_treatment_expert_inclusion/descriptives
asreview wordcloud data/Post_intensive_care_treatment_expert_inclusion.csv -o output/simulation/Post_intensive_care_treatment_expert_inclusion/descriptives/wordcloud_Post_intensive_care_treatment_expert_inclusion.png --width 800 --height 500
asreview wordcloud data/Post_intensive_care_treatment_expert_inclusion.csv -o output/simulation/Post_intensive_care_treatment_expert_inclusion/descriptives/wordcloud_Post_intensive_care_treatment_expert_inclusion_relevant.png --width 800 --height 500 --relevant
asreview wordcloud data/Post_intensive_care_treatment_expert_inclusion.csv -o output/simulation/Post_intensive_care_treatment_expert_inclusion/descriptives/wordcloud_Post_intensive_care_treatment_expert_inclusion_irrelevant.png --width 800 --height 500 --irrelevant

mkdir output/simulation/Post_intensive_care_treatment_fulltext_inclusion/
mkdir output/simulation/Post_intensive_care_treatment_fulltext_inclusion/descriptives
asreview wordcloud data/Post_intensive_care_treatment_fulltext_inclusion.csv -o output/simulation/Post_intensive_care_treatment_fulltext_inclusion/descriptives/wordcloud_Post_intensive_care_treatment_fulltext_inclusion.png --width 800 --height 500
asreview wordcloud data/Post_intensive_care_treatment_fulltext_inclusion.csv -o output/simulation/Post_intensive_care_treatment_fulltext_inclusion/descriptives/wordcloud_Post_intensive_care_treatment_fulltext_inclusion_relevant.png --width 800 --height 500 --relevant
asreview wordcloud data/Post_intensive_care_treatment_fulltext_inclusion.csv -o output/simulation/Post_intensive_care_treatment_fulltext_inclusion/descriptives/wordcloud_Post_intensive_care_treatment_fulltext_inclusion_irrelevant.png --width 800 --height 500 --irrelevant

mkdir output/simulation/Post_intensive_care_treatment_noisy_inclusion/
mkdir output/simulation/Post_intensive_care_treatment_noisy_inclusion/descriptives
asreview wordcloud data/Post_intensive_care_treatment_noisy_inclusion.csv -o output/simulation/Post_intensive_care_treatment_noisy_inclusion/descriptives/wordcloud_Post_intensive_care_treatment_noisy_inclusion.png --width 800 --height 500
asreview wordcloud data/Post_intensive_care_treatment_noisy_inclusion.csv -o output/simulation/Post_intensive_care_treatment_noisy_inclusion/descriptives/wordcloud_Post_intensive_care_treatment_noisy_inclusion_relevant.png --width 800 --height 500 --relevant
asreview wordcloud data/Post_intensive_care_treatment_noisy_inclusion.csv -o output/simulation/Post_intensive_care_treatment_noisy_inclusion/descriptives/wordcloud_Post_intensive_care_treatment_noisy_inclusion_irrelevant.png --width 800 --height 500 --irrelevant

mkdir output/simulation/Pregnancy_medication_expert_inclusion/
mkdir output/simulation/Pregnancy_medication_expert_inclusion/descriptives
asreview wordcloud data/Pregnancy_medication_expert_inclusion.csv -o output/simulation/Pregnancy_medication_expert_inclusion/descriptives/wordcloud_Pregnancy_medication_expert_inclusion.png --width 800 --height 500
asreview wordcloud data/Pregnancy_medication_expert_inclusion.csv -o output/simulation/Pregnancy_medication_expert_inclusion/descriptives/wordcloud_Pregnancy_medication_expert_inclusion_relevant.png --width 800 --height 500 --relevant
asreview wordcloud data/Pregnancy_medication_expert_inclusion.csv -o output/simulation/Pregnancy_medication_expert_inclusion/descriptives/wordcloud_Pregnancy_medication_expert_inclusion_irrelevant.png --width 800 --height 500 --irrelevant

mkdir output/simulation/Pregnancy_medication_fulltext_inclusion/
mkdir output/simulation/Pregnancy_medication_fulltext_inclusion/descriptives
asreview wordcloud data/Pregnancy_medication_fulltext_inclusion.csv -o output/simulation/Pregnancy_medication_fulltext_inclusion/descriptives/wordcloud_Pregnancy_medication_fulltext_inclusion.png --width 800 --height 500
asreview wordcloud data/Pregnancy_medication_fulltext_inclusion.csv -o output/simulation/Pregnancy_medication_fulltext_inclusion/descriptives/wordcloud_Pregnancy_medication_fulltext_inclusion_relevant.png --width 800 --height 500 --relevant
asreview wordcloud data/Pregnancy_medication_fulltext_inclusion.csv -o output/simulation/Pregnancy_medication_fulltext_inclusion/descriptives/wordcloud_Pregnancy_medication_fulltext_inclusion_irrelevant.png --width 800 --height 500 --irrelevant

mkdir output/simulation/Pregnancy_medication_noisy_inclusion/
mkdir output/simulation/Pregnancy_medication_noisy_inclusion/descriptives
asreview wordcloud data/Pregnancy_medication_noisy_inclusion.csv -o output/simulation/Pregnancy_medication_noisy_inclusion/descriptives/wordcloud_Pregnancy_medication_noisy_inclusion.png --width 800 --height 500
asreview wordcloud data/Pregnancy_medication_noisy_inclusion.csv -o output/simulation/Pregnancy_medication_noisy_inclusion/descriptives/wordcloud_Pregnancy_medication_noisy_inclusion_relevant.png --width 800 --height 500 --relevant
asreview wordcloud data/Pregnancy_medication_noisy_inclusion.csv -o output/simulation/Pregnancy_medication_noisy_inclusion/descriptives/wordcloud_Pregnancy_medication_noisy_inclusion_irrelevant.png --width 800 --height 500 --irrelevant

mkdir output/simulation/Shoulder_replacement_diagnostic_expert_inclusion/
mkdir output/simulation/Shoulder_replacement_diagnostic_expert_inclusion/descriptives
asreview wordcloud data/Shoulder_replacement_diagnostic_expert_inclusion.csv -o output/simulation/Shoulder_replacement_diagnostic_expert_inclusion/descriptives/wordcloud_Shoulder_replacement_diagnostic_expert_inclusion.png --width 800 --height 500
asreview wordcloud data/Shoulder_replacement_diagnostic_expert_inclusion.csv -o output/simulation/Shoulder_replacement_diagnostic_expert_inclusion/descriptives/wordcloud_Shoulder_replacement_diagnostic_expert_inclusion_relevant.png --width 800 --height 500 --relevant
asreview wordcloud data/Shoulder_replacement_diagnostic_expert_inclusion.csv -o output/simulation/Shoulder_replacement_diagnostic_expert_inclusion/descriptives/wordcloud_Shoulder_replacement_diagnostic_expert_inclusion_irrelevant.png --width 800 --height 500 --irrelevant

mkdir output/simulation/Shoulder_replacement_diagnostic_fulltext_inclusion/
mkdir output/simulation/Shoulder_replacement_diagnostic_fulltext_inclusion/descriptives
asreview wordcloud data/Shoulder_replacement_diagnostic_fulltext_inclusion.csv -o output/simulation/Shoulder_replacement_diagnostic_fulltext_inclusion/descriptives/wordcloud_Shoulder_replacement_diagnostic_fulltext_inclusion.png --width 800 --height 500
asreview wordcloud data/Shoulder_replacement_diagnostic_fulltext_inclusion.csv -o output/simulation/Shoulder_replacement_diagnostic_fulltext_inclusion/descriptives/wordcloud_Shoulder_replacement_diagnostic_fulltext_inclusion_relevant.png --width 800 --height 500 --relevant
asreview wordcloud data/Shoulder_replacement_diagnostic_fulltext_inclusion.csv -o output/simulation/Shoulder_replacement_diagnostic_fulltext_inclusion/descriptives/wordcloud_Shoulder_replacement_diagnostic_fulltext_inclusion_irrelevant.png --width 800 --height 500 --irrelevant

mkdir output/simulation/Shoulder_replacement_diagnostic_noisy_inclusion/
mkdir output/simulation/Shoulder_replacement_diagnostic_noisy_inclusion/descriptives
asreview wordcloud data/Shoulder_replacement_diagnostic_noisy_inclusion.csv -o output/simulation/Shoulder_replacement_diagnostic_noisy_inclusion/descriptives/wordcloud_Shoulder_replacement_diagnostic_noisy_inclusion.png --width 800 --height 500
asreview wordcloud data/Shoulder_replacement_diagnostic_noisy_inclusion.csv -o output/simulation/Shoulder_replacement_diagnostic_noisy_inclusion/descriptives/wordcloud_Shoulder_replacement_diagnostic_noisy_inclusion_relevant.png --width 800 --height 500 --relevant
asreview wordcloud data/Shoulder_replacement_diagnostic_noisy_inclusion.csv -o output/simulation/Shoulder_replacement_diagnostic_noisy_inclusion/descriptives/wordcloud_Shoulder_replacement_diagnostic_noisy_inclusion_irrelevant.png --width 800 --height 500 --irrelevant

mkdir output/simulation/Shoulder_replacement_surgery_expert_inclusion/
mkdir output/simulation/Shoulder_replacement_surgery_expert_inclusion/descriptives
asreview wordcloud data/Shoulder_replacement_surgery_expert_inclusion.csv -o output/simulation/Shoulder_replacement_surgery_expert_inclusion/descriptives/wordcloud_Shoulder_replacement_surgery_expert_inclusion.png --width 800 --height 500
asreview wordcloud data/Shoulder_replacement_surgery_expert_inclusion.csv -o output/simulation/Shoulder_replacement_surgery_expert_inclusion/descriptives/wordcloud_Shoulder_replacement_surgery_expert_inclusion_relevant.png --width 800 --height 500 --relevant
asreview wordcloud data/Shoulder_replacement_surgery_expert_inclusion.csv -o output/simulation/Shoulder_replacement_surgery_expert_inclusion/descriptives/wordcloud_Shoulder_replacement_surgery_expert_inclusion_irrelevant.png --width 800 --height 500 --irrelevant

mkdir output/simulation/Shoulder_replacement_surgery_fulltext_inclusion/
mkdir output/simulation/Shoulder_replacement_surgery_fulltext_inclusion/descriptives
asreview wordcloud data/Shoulder_replacement_surgery_fulltext_inclusion.csv -o output/simulation/Shoulder_replacement_surgery_fulltext_inclusion/descriptives/wordcloud_Shoulder_replacement_surgery_fulltext_inclusion.png --width 800 --height 500
asreview wordcloud data/Shoulder_replacement_surgery_fulltext_inclusion.csv -o output/simulation/Shoulder_replacement_surgery_fulltext_inclusion/descriptives/wordcloud_Shoulder_replacement_surgery_fulltext_inclusion_relevant.png --width 800 --height 500 --relevant
asreview wordcloud data/Shoulder_replacement_surgery_fulltext_inclusion.csv -o output/simulation/Shoulder_replacement_surgery_fulltext_inclusion/descriptives/wordcloud_Shoulder_replacement_surgery_fulltext_inclusion_irrelevant.png --width 800 --height 500 --irrelevant

mkdir output/simulation/Shoulder_replacement_surgery_noisy_inclusion/
mkdir output/simulation/Shoulder_replacement_surgery_noisy_inclusion/descriptives
asreview wordcloud data/Shoulder_replacement_surgery_noisy_inclusion.csv -o output/simulation/Shoulder_replacement_surgery_noisy_inclusion/descriptives/wordcloud_Shoulder_replacement_surgery_noisy_inclusion.png --width 800 --height 500
asreview wordcloud data/Shoulder_replacement_surgery_noisy_inclusion.csv -o output/simulation/Shoulder_replacement_surgery_noisy_inclusion/descriptives/wordcloud_Shoulder_replacement_surgery_noisy_inclusion_relevant.png --width 800 --height 500 --relevant
asreview wordcloud data/Shoulder_replacement_surgery_noisy_inclusion.csv -o output/simulation/Shoulder_replacement_surgery_noisy_inclusion/descriptives/wordcloud_Shoulder_replacement_surgery_noisy_inclusion_irrelevant.png --width 800 --height 500 --irrelevant

mkdir output/simulation/Shoulderdystocia_positioning_expert_inclusion/
mkdir output/simulation/Shoulderdystocia_positioning_expert_inclusion/descriptives
asreview wordcloud data/Shoulderdystocia_positioning_expert_inclusion.csv -o output/simulation/Shoulderdystocia_positioning_expert_inclusion/descriptives/wordcloud_Shoulderdystocia_positioning_expert_inclusion.png --width 800 --height 500
asreview wordcloud data/Shoulderdystocia_positioning_expert_inclusion.csv -o output/simulation/Shoulderdystocia_positioning_expert_inclusion/descriptives/wordcloud_Shoulderdystocia_positioning_expert_inclusion_relevant.png --width 800 --height 500 --relevant
asreview wordcloud data/Shoulderdystocia_positioning_expert_inclusion.csv -o output/simulation/Shoulderdystocia_positioning_expert_inclusion/descriptives/wordcloud_Shoulderdystocia_positioning_expert_inclusion_irrelevant.png --width 800 --height 500 --irrelevant

mkdir output/simulation/Shoulderdystocia_positioning_fulltext_inclusion/
mkdir output/simulation/Shoulderdystocia_positioning_fulltext_inclusion/descriptives
asreview wordcloud data/Shoulderdystocia_positioning_fulltext_inclusion.csv -o output/simulation/Shoulderdystocia_positioning_fulltext_inclusion/descriptives/wordcloud_Shoulderdystocia_positioning_fulltext_inclusion.png --width 800 --height 500
asreview wordcloud data/Shoulderdystocia_positioning_fulltext_inclusion.csv -o output/simulation/Shoulderdystocia_positioning_fulltext_inclusion/descriptives/wordcloud_Shoulderdystocia_positioning_fulltext_inclusion_relevant.png --width 800 --height 500 --relevant
asreview wordcloud data/Shoulderdystocia_positioning_fulltext_inclusion.csv -o output/simulation/Shoulderdystocia_positioning_fulltext_inclusion/descriptives/wordcloud_Shoulderdystocia_positioning_fulltext_inclusion_irrelevant.png --width 800 --height 500 --irrelevant

mkdir output/simulation/Shoulderdystocia_positioning_noisy_inclusion/
mkdir output/simulation/Shoulderdystocia_positioning_noisy_inclusion/descriptives
asreview wordcloud data/Shoulderdystocia_positioning_noisy_inclusion.csv -o output/simulation/Shoulderdystocia_positioning_noisy_inclusion/descriptives/wordcloud_Shoulderdystocia_positioning_noisy_inclusion.png --width 800 --height 500
asreview wordcloud data/Shoulderdystocia_positioning_noisy_inclusion.csv -o output/simulation/Shoulderdystocia_positioning_noisy_inclusion/descriptives/wordcloud_Shoulderdystocia_positioning_noisy_inclusion_relevant.png --width 800 --height 500 --relevant
asreview wordcloud data/Shoulderdystocia_positioning_noisy_inclusion.csv -o output/simulation/Shoulderdystocia_positioning_noisy_inclusion/descriptives/wordcloud_Shoulderdystocia_positioning_noisy_inclusion_irrelevant.png --width 800 --height 500 --irrelevant

mkdir output/simulation/Shoulderdystocia_recurrence_expert_inclusion/
mkdir output/simulation/Shoulderdystocia_recurrence_expert_inclusion/descriptives
asreview wordcloud data/Shoulderdystocia_recurrence_expert_inclusion.csv -o output/simulation/Shoulderdystocia_recurrence_expert_inclusion/descriptives/wordcloud_Shoulderdystocia_recurrence_expert_inclusion.png --width 800 --height 500
asreview wordcloud data/Shoulderdystocia_recurrence_expert_inclusion.csv -o output/simulation/Shoulderdystocia_recurrence_expert_inclusion/descriptives/wordcloud_Shoulderdystocia_recurrence_expert_inclusion_relevant.png --width 800 --height 500 --relevant
asreview wordcloud data/Shoulderdystocia_recurrence_expert_inclusion.csv -o output/simulation/Shoulderdystocia_recurrence_expert_inclusion/descriptives/wordcloud_Shoulderdystocia_recurrence_expert_inclusion_irrelevant.png --width 800 --height 500 --irrelevant

mkdir output/simulation/Shoulderdystocia_recurrence_fulltext_inclusion/
mkdir output/simulation/Shoulderdystocia_recurrence_fulltext_inclusion/descriptives
asreview wordcloud data/Shoulderdystocia_recurrence_fulltext_inclusion.csv -o output/simulation/Shoulderdystocia_recurrence_fulltext_inclusion/descriptives/wordcloud_Shoulderdystocia_recurrence_fulltext_inclusion.png --width 800 --height 500
asreview wordcloud data/Shoulderdystocia_recurrence_fulltext_inclusion.csv -o output/simulation/Shoulderdystocia_recurrence_fulltext_inclusion/descriptives/wordcloud_Shoulderdystocia_recurrence_fulltext_inclusion_relevant.png --width 800 --height 500 --relevant
asreview wordcloud data/Shoulderdystocia_recurrence_fulltext_inclusion.csv -o output/simulation/Shoulderdystocia_recurrence_fulltext_inclusion/descriptives/wordcloud_Shoulderdystocia_recurrence_fulltext_inclusion_irrelevant.png --width 800 --height 500 --irrelevant

mkdir output/simulation/Shoulderdystocia_recurrence_noisy_inclusion/
mkdir output/simulation/Shoulderdystocia_recurrence_noisy_inclusion/descriptives
asreview wordcloud data/Shoulderdystocia_recurrence_noisy_inclusion.csv -o output/simulation/Shoulderdystocia_recurrence_noisy_inclusion/descriptives/wordcloud_Shoulderdystocia_recurrence_noisy_inclusion.png --width 800 --height 500
asreview wordcloud data/Shoulderdystocia_recurrence_noisy_inclusion.csv -o output/simulation/Shoulderdystocia_recurrence_noisy_inclusion/descriptives/wordcloud_Shoulderdystocia_recurrence_noisy_inclusion_relevant.png --width 800 --height 500 --relevant
asreview wordcloud data/Shoulderdystocia_recurrence_noisy_inclusion.csv -o output/simulation/Shoulderdystocia_recurrence_noisy_inclusion/descriptives/wordcloud_Shoulderdystocia_recurrence_noisy_inclusion_irrelevant.png --width 800 --height 500 --irrelevant

mkdir output/simulation/Total_knee_replacement_expert_inclusion/
mkdir output/simulation/Total_knee_replacement_expert_inclusion/descriptives
asreview wordcloud data/Total_knee_replacement_expert_inclusion.csv -o output/simulation/Total_knee_replacement_expert_inclusion/descriptives/wordcloud_Total_knee_replacement_expert_inclusion.png --width 800 --height 500
asreview wordcloud data/Total_knee_replacement_expert_inclusion.csv -o output/simulation/Total_knee_replacement_expert_inclusion/descriptives/wordcloud_Total_knee_replacement_expert_inclusion_relevant.png --width 800 --height 500 --relevant
asreview wordcloud data/Total_knee_replacement_expert_inclusion.csv -o output/simulation/Total_knee_replacement_expert_inclusion/descriptives/wordcloud_Total_knee_replacement_expert_inclusion_irrelevant.png --width 800 --height 500 --irrelevant

mkdir output/simulation/Total_knee_replacement_fulltext_inclusion/
mkdir output/simulation/Total_knee_replacement_fulltext_inclusion/descriptives
asreview wordcloud data/Total_knee_replacement_fulltext_inclusion.csv -o output/simulation/Total_knee_replacement_fulltext_inclusion/descriptives/wordcloud_Total_knee_replacement_fulltext_inclusion.png --width 800 --height 500
asreview wordcloud data/Total_knee_replacement_fulltext_inclusion.csv -o output/simulation/Total_knee_replacement_fulltext_inclusion/descriptives/wordcloud_Total_knee_replacement_fulltext_inclusion_relevant.png --width 800 --height 500 --relevant
asreview wordcloud data/Total_knee_replacement_fulltext_inclusion.csv -o output/simulation/Total_knee_replacement_fulltext_inclusion/descriptives/wordcloud_Total_knee_replacement_fulltext_inclusion_irrelevant.png --width 800 --height 500 --irrelevant

mkdir output/simulation/Total_knee_replacement_noisy_inclusion/
mkdir output/simulation/Total_knee_replacement_noisy_inclusion/descriptives
asreview wordcloud data/Total_knee_replacement_noisy_inclusion.csv -o output/simulation/Total_knee_replacement_noisy_inclusion/descriptives/wordcloud_Total_knee_replacement_noisy_inclusion.png --width 800 --height 500
asreview wordcloud data/Total_knee_replacement_noisy_inclusion.csv -o output/simulation/Total_knee_replacement_noisy_inclusion/descriptives/wordcloud_Total_knee_replacement_noisy_inclusion_relevant.png --width 800 --height 500 --relevant
asreview wordcloud data/Total_knee_replacement_noisy_inclusion.csv -o output/simulation/Total_knee_replacement_noisy_inclusion/descriptives/wordcloud_Total_knee_replacement_noisy_inclusion_irrelevant.png --width 800 --height 500 --irrelevant

mkdir output/simulation/Vascular_access_expert_inclusion/
mkdir output/simulation/Vascular_access_expert_inclusion/descriptives
asreview wordcloud data/Vascular_access_expert_inclusion.csv -o output/simulation/Vascular_access_expert_inclusion/descriptives/wordcloud_Vascular_access_expert_inclusion.png --width 800 --height 500
asreview wordcloud data/Vascular_access_expert_inclusion.csv -o output/simulation/Vascular_access_expert_inclusion/descriptives/wordcloud_Vascular_access_expert_inclusion_relevant.png --width 800 --height 500 --relevant
asreview wordcloud data/Vascular_access_expert_inclusion.csv -o output/simulation/Vascular_access_expert_inclusion/descriptives/wordcloud_Vascular_access_expert_inclusion_irrelevant.png --width 800 --height 500 --irrelevant

mkdir output/simulation/Vascular_access_fulltext_inclusion/
mkdir output/simulation/Vascular_access_fulltext_inclusion/descriptives
asreview wordcloud data/Vascular_access_fulltext_inclusion.csv -o output/simulation/Vascular_access_fulltext_inclusion/descriptives/wordcloud_Vascular_access_fulltext_inclusion.png --width 800 --height 500
asreview wordcloud data/Vascular_access_fulltext_inclusion.csv -o output/simulation/Vascular_access_fulltext_inclusion/descriptives/wordcloud_Vascular_access_fulltext_inclusion_relevant.png --width 800 --height 500 --relevant
asreview wordcloud data/Vascular_access_fulltext_inclusion.csv -o output/simulation/Vascular_access_fulltext_inclusion/descriptives/wordcloud_Vascular_access_fulltext_inclusion_irrelevant.png --width 800 --height 500 --irrelevant

mkdir output/simulation/Vascular_access_noisy_inclusion/
mkdir output/simulation/Vascular_access_noisy_inclusion/descriptives
asreview wordcloud data/Vascular_access_noisy_inclusion.csv -o output/simulation/Vascular_access_noisy_inclusion/descriptives/wordcloud_Vascular_access_noisy_inclusion.png --width 800 --height 500
asreview wordcloud data/Vascular_access_noisy_inclusion.csv -o output/simulation/Vascular_access_noisy_inclusion/descriptives/wordcloud_Vascular_access_noisy_inclusion_relevant.png --width 800 --height 500 --relevant
asreview wordcloud data/Vascular_access_noisy_inclusion.csv -o output/simulation/Vascular_access_noisy_inclusion/descriptives/wordcloud_Vascular_access_noisy_inclusion_irrelevant.png --width 800 --height 500 --irrelevant
